CREATE TABLE `COMPANIES` (
    `COMPANYID` INT NOT NULL AUTO_INCREMENT,
    `COMPANYNAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`COMPANYID`)
);

CREATE TABLE `ROLES` (
    `ROLEID` INT NOT NULL AUTO_INCREMENT,
    `ROLENAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ROLEID`)
) CREATE TABLE `USERS` (
    `USERID` INT NOT NULL AUTO_INCREMENT,
    `FIRSTNAME` VARCHAR(255) NOT NULL,
    `LASTNAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `ROLEID` INT DEFAULT NULL,
    `COMPANYID` INT DEFAULT NULL,
    PRIMARY KEY (`USERID`),
    KEY `ROLEID` (`ROLEID`),
    KEY `COMPANYID` (`COMPANYID`),
    CONSTRAINT `USERS_IBFK_1` FOREIGN KEY (`ROLEID`) REFERENCES `ROLES` (`ROLEID`),
    CONSTRAINT `USERS_IBFK_2` FOREIGN KEY (`COMPANYID`) REFERENCES `COMPANIES` (`COMPANYID`)
);