CREATE TABLE `COMPANIES` (
    `COMPANYID` INT NOT NULL AUTO_INCREMENT,
    `COMPANYNAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`COMPANYID`)
);

CREATE TABLE `ROLES` (
    `ROLEID` INT NOT NULL AUTO_INCREMENT,
    `ROLENAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ROLEID`)
);

CREATE TABLE `USERS` (
    `USERID` INT NOT NULL AUTO_INCREMENT,
    `FIRSTNAME` VARCHAR(255) NOT NULL,
    `LASTNAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255),
    `ROLEID` INT DEFAULT NULL,
    `COMPANYID` INT DEFAULT NULL,
    `TAG` VARCHAR(255),
    `FILTERS` VARCHAR(255),
    `LOGIN_METHOD` ENUM('GOOGLE', 'MICROSOFT', 'VITRA') NOT NULL,
    `TEMP_PASSWORD` VARCHAR(255),
    PRIMARY KEY (`USERID`),
    KEY `ROLEID` (`ROLEID`),
    KEY `COMPANYID` (`COMPANYID`),
    CONSTRAINT `USERS_IBFK_1` FOREIGN KEY (`ROLEID`) REFERENCES `ROLES` (`ROLEID`),
    CONSTRAINT `USERS_IBFK_2` FOREIGN KEY (`COMPANYID`) REFERENCES `COMPANIES` (`COMPANYID`)
);

ALTER TABLE USERS ADD COLUMN ISACTIVE BOOLEAN DEFAULT TRUE;

CREATE TABLE USER_BACKUP LIKE USERS;


