### Email Request
GET http://localhost:5000/api/sendmail HTTP/1.1


### Login Request
POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

### Authed Request
GET http://localhost:5000/api/authed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImlhdCI6MTY4OTE4MTg3NX0.W-4HgPs7ms9MT5AHH3pQ9c-0HXS0oAcv82eDfkvtRkA