### Prisma test
GET http://localhost:5000/prismatest

### Email Request
GET http://localhost:5000/api/sendmail HTTP/1.1


### Login Request
POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "manager@company1.com",
  "password": "password"
}

### Authed Request
GET http://localhost:5000/api/authed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYW5hZ2VyQGNvbXBhbnkxLmNvbSIsImlhdCI6MTY4OTIyNDk5N30.W5GuZWhh3woOr87dUSk5VRz7Gy78Zt1R93OhRHC8tRE